### ISSUE TITLE
[BUG] Lawnchair crashes frequently after updating to 15.Beta 1

### ISSUE THREAD

**Issue by rrkia** [Deletescape-Media/Lawnchair#5888]
### Describe the bug

- After updating from 14 to 15.beta1, every settings disappeared. 
- After adding something or modifying some settings in Lawnchair, it crashes, and deletes all the settings. Sometimes it is even impossible to go back to desktop.

### Steps to reproduce

1. Install Quickswitch, set Lawnchair as the default launcher, and update Lawnchair from 14 to 15beta1.
2. (Icons disappeared)
3. Modify any setting or add any icon.
4. (Lawnchair begin to crash frequently)

### Expected behavior

It works normally.

### Device information

- Device: Xiaomi Pad 6 Pro
- OS: HyperOS 1.0.12(Android 14)

### App version

15.Beta 1

### Additional context

FATAL EXCEPTION: main
Process: app.lawnchair, PID: 28685
java.lang.NoSuchMethodError: No interface method destroyInputConsumer(Landroid/os/IBinder;I)Z in class Landroid/view/IWindowManager; or its super classes (declaration of 'android.view.IWindowManager' appears in /system/framework/framework.jar!classes4.dex)
	at com.android.systemui.shared.system.InputConsumerController.registerInputConsumer(Unknown Source:14)
	at com.android.quickstep.TouchInteractionService.onUserUnlocked(Unknown Source:72)
	at com.android.quickstep.j8.run(Unknown Source:2)
	at com.android.launcher3.util.RunnableList.add(Unknown Source:7)
	at com.android.launcher3.util.LockedUserState.runOnUserUnlocked(Unknown Source:7)
	at com.android.quickstep.TouchInteractionService.onCreate(Unknown Source:118)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4878)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
